name: Dexter AI Code Review Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]
  
permissions: write-all

jobs:
  pr_review:  # Unique identifier for the job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DEXTERAIDEV_ACCOUNT_TOKEN }}
      - name: Code Review
        uses: suitedaces/dexter-ai@main
        with:
          GITHUB_TOKEN: ${{ secrets.DEXTERAIDEV_ACCOUNT_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-4"
